### ISSUE TITLE
Feature: API methods to encapsulate catching ChannelClosed exception and return success flag instead

### ISSUE THREAD

**Issue by nirvana-msu** [tbug/aiochannel#11]
A suggestion to add high-level API methods methods that, instead of throwing `ChannelClosed`, return a boolean on whether operation was successfull vs channel is closed/closing.

Currently, whenever you use `put` / `put_nowait`, you always have to wrap it in a `try` block to catch and handle `ChannelClosed` exception.  It would be a lot more convenient if that detail could be hidden inside a higher-level API and we just got a boolean instead.

The API could look something like this:
```python
async def try_put(self, item) -> bool:
    """Try to put item into the channel, returning boolean whether operation succeeded or if the channel is closed/closing."""
    try:
        await self.put(item)
    except ChannelClosed:
        return False
    return True
```
(and similar for  `try_put_nowait`)

For example, currently if I have to do something only if operation succeeds, I need to write code like:
```python
try:
    await channel.put(item)
    # do something on success
except ChannelClosed:
    pass
```
with new API:
```python
if await channel.try_put(item):
    # do something on success
```

It also makes it especially convenient to use with iterable operators like `filter` (or its async counterparts).
E.g. looping through a list of channels, putting a message into each one, and filering out closed channels, can all be done in one line:
```python
channels = list(filter(lambda channel: channel.try_put_nowait(item), channels))
```

**Comment by tudborg** [comment]
@nirvana-msu Sorry for the long wait. I don't have notifications enabled for this repo.

Thank you for taking the time to post a good example, and your own usecase. It is very helpful.
If this issue is still relevant to you:

My general position is that hiding the reason for a failure from the caller isn't a good pattern, however it's been years since I actively participated in the Python community, and I'll lean into what is currently considered pythonic, so if you can point me to other popular libraries that have chosen to do so, I'm open to this change.

The current API already allow you to check if a channel would raise `ChannelClosed` or `ChannelFull` by checking for

```python
channel.closed()
channel.full()
```

However I do understand that having a convenience API would make certain interactions simpler for the caller.
