### ISSUE TITLE
As of 3.10, the *loop* parameter was removed from Event() since it is no longer necessary

### ISSUE THREAD

**Issue by alvassin** [tbug/aiochannel#4]
Unable to upgrade to the 3.10 python. Could you please skip loop parameter for python versions with deprecated loop parameter?

**Comment by alvassin** [comment]
I tried to make PR, but tests fail becase nose does not work with python 3.10 (latest commit was done 5 years ago).
If it is acceptable, I can change nosetests to pytest and add python 3.10 support.

**Comment by tudborg** [comment]
Hey @alvassin, Sorry, I didn't see your issue :)

I have just added Python 3.10 compatibility.
I was already using `coverage.py`, so I just used that as runner instead.

Feel free to take a look, it's been years since I actively did Python, so you might be able to help point out if there are better tools for the job than what I'm currently using.

**Comment by tudborg** [comment]
I've published a new version to pypi that should remove some of the uses of loop.
This will allow you to run it on 3.10.
I needed to keep some of it in for now to service python 3.6 to 3.10.
Once I feel I can narrow the support to 3.7+ there is a lot of quality-of-life I can do to the code, which also includes all of these deprecations.

Hope this works for you.

**Comment by alvassin** [comment]
Thank you very much for your help!
